services:
  redis:
    image: redis:latest
    container_name: proselyte-redis
    ports:
      - "6379:6379"
    networks:
      - proselyte-redis-net

  redis-insight:
    image: redis/redisinsight:latest
    container_name: proselyte-redisinsight
    restart: always
    depends_on:
      - redis
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
    networks:
      - proselyte-redis-net

volumes:
  redis-insight:

networks:
  proselyte-redis-net:
    driver: bridge
