services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: core-redis-api
    ports:
      - "8087:8087"
    depends_on:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/core_redis
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - core-redis-net
  redis:
    image: redis/redis-stack-server:latest
    container_name: core-redis
    ports:
      - "6379:6379"
    networks:
      - core-redis-net

  postgres:
    image: postgres:17.7-alpine
    container_name: core-postgres
    environment:
      POSTGRES_DB: core_redis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - core-redis-net

  redis-insight:
    image: redis/redisinsight:latest
    container_name: core-redisinsight
    restart: always
    depends_on:
      - redis
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
    networks:
      - core-redis-net

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: core-redis-ui
    ports:
      - "3000:3000"
    environment:
      - API_BASE=http://core-redis-api:8087/api/v1
      - REDIS_URL=redis://core-redis:6379
    depends_on:
      - api
    networks:
      - core-redis-net

volumes:
  redis-insight:
  pgdata:

networks:
  core-redis-net:
    driver: bridge
